name: valt
description: Valt is a Flutter plugin that enables easy reading and writing of simple key-value pairs with AES encryption for secure local storage.

homepage: https://github.com/mufassalhussain/valt
version: 0.0.4
environment:
  sdk: ">=2.17.0 <4.0.0"
  
dependencies:
  crypto: 
  encrypt:
  path_provider:
  universal_html: 
dev_dependencies:
  flutter_test:
    sdk: flutter
