name: valt
description: Valt is a Flutter plugin that enables easy reading and writing of simple key-value pairs with AES encryption for secure local storage.

homepage: https://github.com/mufassalhussain/valt
version: 0.0.1+1
environment:
  sdk: ">=2.17.0 <4.0.0"
  
dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  path_provider: ^2.0.14
dev_dependencies:
  flutter_test:
    sdk: flutter
